//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/Others/Taffy/Input/PlayingInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Others/Taffy/Input/PlayingInputAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayingInputAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayingInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayingInputAction"",
    ""maps"": [
        {
            ""name"": ""PlayerA"",
            ""id"": ""b7e21220-69e4-43fe-bedb-78148284c243"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""0c001642-722e-4a7b-895d-e3bb1e2ae4ce"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Evacuate"",
                    ""type"": ""Button"",
                    ""id"": ""a59c323d-41d8-42e7-a1f8-566880652e4b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenOrCloseBag"",
                    ""type"": ""Button"",
                    ""id"": ""5731ee8e-507c-4d6f-97b2-769d42530150"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseProp"",
                    ""type"": ""Value"",
                    ""id"": ""f9897845-3394-481c-a839-2af01f08fd9c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DiscardProp"",
                    ""type"": ""Button"",
                    ""id"": ""23b26f17-7913-45f8-a3d2-66545bb210c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenOrCloseContainer"",
                    ""type"": ""Button"",
                    ""id"": ""fd348ced-a924-4b90-84d3-d0903564d9fd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReplaceProp"",
                    ""type"": ""Button"",
                    ""id"": ""619409dd-2691-4a11-8346-9bf640202180"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseProp"",
                    ""type"": ""Button"",
                    ""id"": ""4546edf0-0141-48dc-bd81-f3b60022b918"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""7404dc12-efc6-439c-8e47-2642adeaea7f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchIndex"",
                    ""type"": ""Button"",
                    ""id"": ""9f063fc3-8005-4705-8175-731c865894f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f7acbb34-d44b-49ab-b21f-fea12704d4dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a19c067d-9bf3-4d4f-882f-c3bf87bd5953"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e11f0ec6-4a86-441a-83af-282046da4807"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c2f18d8-db22-450c-949d-52ee0260275e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b5e408e8-5d4b-469f-b0e8-ca150993aaf7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e654b7c4-108f-4324-9ca6-9ffc0929f8a5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Evacuate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a809164-e878-49b3-b328-b1ecf561d25d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenOrCloseBag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1e7ef057-456f-4e02-a246-cf55007e3f45"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fddfbeab-c4d8-4223-8e17-67831f72b8df"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5af194b9-ced5-4e91-8486-ad6b1ba2dc6b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""eea3c061-6c39-44e7-8040-0cceb8f609be"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""abd99ab0-11a6-482a-8d35-1e9f0835f7e2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3315ab03-9a9c-4446-a1b2-b89fa7fd9109"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscardProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a49e3113-14f9-4994-a9c6-a3e3202264c2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenOrCloseContainer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16edeb7a-1cc6-4cc3-bf04-e738f622b5b8"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReplaceProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b647e5af-d4cb-4969-8a26-ea3f28548fa2"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898e0c4f-1a3a-4940-990a-b7a41661ff14"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""642406dd-7e16-4246-81d9-c7abd8b96c51"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerB"",
            ""id"": ""e8ea7231-f26a-4960-a141-4edb27022cb6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c1656e58-4b9c-4755-a23d-856241622732"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenOrCloseContainer"",
                    ""type"": ""Button"",
                    ""id"": ""035382b8-a66e-4a43-ade5-9e56292ee7bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DiscardProp"",
                    ""type"": ""Button"",
                    ""id"": ""08e85b6a-4c57-4cee-b601-651255a87de5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseProp"",
                    ""type"": ""Value"",
                    ""id"": ""0b2b06aa-577b-409e-bdb3-a48465453eec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Evacuate"",
                    ""type"": ""Button"",
                    ""id"": ""702c07cf-dd84-48be-95e9-a06535d54ced"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenOrCloseBag"",
                    ""type"": ""Button"",
                    ""id"": ""1f7fd4a1-a254-4ca2-9f3d-a976d3eb6374"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReplaceProp"",
                    ""type"": ""Button"",
                    ""id"": ""43727070-e863-4c3b-b935-3198b202a9e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseProp"",
                    ""type"": ""Button"",
                    ""id"": ""03e4389a-3d62-455c-9e11-d2f1b046eaa6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""b1cdf364-2bf0-4f84-b0c1-a90854e1aeff"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchIndex"",
                    ""type"": ""Button"",
                    ""id"": ""22059771-1fe3-4108-a39c-824ce406c18b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b5d140ff-577e-4b3f-a11b-830891312643"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""85ebefdd-f6e1-4045-adcc-800b0b3df8dc"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3439464f-787f-41dc-93bd-82096ca6e57e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""55b30508-ffce-46a8-bb5a-ac2c0e1cc148"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a679ee1-fb76-4f2b-adea-f7ae0b999bf9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d80b34ce-c3be-4c36-abf2-32b1290ea6cc"",
                    ""path"": ""<Keyboard>/numpadPeriod"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenOrCloseContainer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9dff493-0d5b-4984-9303-c4490deee36b"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiscardProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d7d23c48-13cf-415d-90f7-71f5b00a44dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e7d6c3c1-e2ac-494e-8e20-636346a285d9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0b10e67b-455a-42f4-b155-cc33c34a2069"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0365feff-04bb-4b1a-8a2a-9e8a337c3f2a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b099d7e-1d18-4268-b99c-6d48efac9a4c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e275f19d-0c48-458d-8069-713117cd9285"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Evacuate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63e1c4a1-0334-4130-aa5a-fab731aecf5d"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenOrCloseBag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d07846b1-35ae-42b1-858a-4242794a9363"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReplaceProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fe7d184-f4ed-4e0a-aa31-e381b0e7f0b7"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseProp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc5785e0-c356-450d-a073-fb25a9322323"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68e94819-cebe-4ea7-9c63-73fbcf84b364"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerA
        m_PlayerA = asset.FindActionMap("PlayerA", throwIfNotFound: true);
        m_PlayerA_Move = m_PlayerA.FindAction("Move", throwIfNotFound: true);
        m_PlayerA_Evacuate = m_PlayerA.FindAction("Evacuate", throwIfNotFound: true);
        m_PlayerA_OpenOrCloseBag = m_PlayerA.FindAction("OpenOrCloseBag", throwIfNotFound: true);
        m_PlayerA_ChooseProp = m_PlayerA.FindAction("ChooseProp", throwIfNotFound: true);
        m_PlayerA_DiscardProp = m_PlayerA.FindAction("DiscardProp", throwIfNotFound: true);
        m_PlayerA_OpenOrCloseContainer = m_PlayerA.FindAction("OpenOrCloseContainer", throwIfNotFound: true);
        m_PlayerA_ReplaceProp = m_PlayerA.FindAction("ReplaceProp", throwIfNotFound: true);
        m_PlayerA_UseProp = m_PlayerA.FindAction("UseProp", throwIfNotFound: true);
        m_PlayerA_Attack = m_PlayerA.FindAction("Attack", throwIfNotFound: true);
        m_PlayerA_SwitchIndex = m_PlayerA.FindAction("SwitchIndex", throwIfNotFound: true);
        // PlayerB
        m_PlayerB = asset.FindActionMap("PlayerB", throwIfNotFound: true);
        m_PlayerB_Move = m_PlayerB.FindAction("Move", throwIfNotFound: true);
        m_PlayerB_OpenOrCloseContainer = m_PlayerB.FindAction("OpenOrCloseContainer", throwIfNotFound: true);
        m_PlayerB_DiscardProp = m_PlayerB.FindAction("DiscardProp", throwIfNotFound: true);
        m_PlayerB_ChooseProp = m_PlayerB.FindAction("ChooseProp", throwIfNotFound: true);
        m_PlayerB_Evacuate = m_PlayerB.FindAction("Evacuate", throwIfNotFound: true);
        m_PlayerB_OpenOrCloseBag = m_PlayerB.FindAction("OpenOrCloseBag", throwIfNotFound: true);
        m_PlayerB_ReplaceProp = m_PlayerB.FindAction("ReplaceProp", throwIfNotFound: true);
        m_PlayerB_UseProp = m_PlayerB.FindAction("UseProp", throwIfNotFound: true);
        m_PlayerB_Attack = m_PlayerB.FindAction("Attack", throwIfNotFound: true);
        m_PlayerB_SwitchIndex = m_PlayerB.FindAction("SwitchIndex", throwIfNotFound: true);
    }

    ~@PlayingInputAction()
    {
        UnityEngine.Debug.Assert(!m_PlayerA.enabled, "This will cause a leak and performance issues, PlayingInputAction.PlayerA.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerB.enabled, "This will cause a leak and performance issues, PlayingInputAction.PlayerB.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerA
    private readonly InputActionMap m_PlayerA;
    private List<IPlayerAActions> m_PlayerAActionsCallbackInterfaces = new List<IPlayerAActions>();
    private readonly InputAction m_PlayerA_Move;
    private readonly InputAction m_PlayerA_Evacuate;
    private readonly InputAction m_PlayerA_OpenOrCloseBag;
    private readonly InputAction m_PlayerA_ChooseProp;
    private readonly InputAction m_PlayerA_DiscardProp;
    private readonly InputAction m_PlayerA_OpenOrCloseContainer;
    private readonly InputAction m_PlayerA_ReplaceProp;
    private readonly InputAction m_PlayerA_UseProp;
    private readonly InputAction m_PlayerA_Attack;
    private readonly InputAction m_PlayerA_SwitchIndex;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerA".
    /// </summary>
    public struct PlayerAActions
    {
        private @PlayingInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerAActions(@PlayingInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_PlayerA_Move;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/Evacuate".
        /// </summary>
        public InputAction @Evacuate => m_Wrapper.m_PlayerA_Evacuate;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/OpenOrCloseBag".
        /// </summary>
        public InputAction @OpenOrCloseBag => m_Wrapper.m_PlayerA_OpenOrCloseBag;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/ChooseProp".
        /// </summary>
        public InputAction @ChooseProp => m_Wrapper.m_PlayerA_ChooseProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/DiscardProp".
        /// </summary>
        public InputAction @DiscardProp => m_Wrapper.m_PlayerA_DiscardProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/OpenOrCloseContainer".
        /// </summary>
        public InputAction @OpenOrCloseContainer => m_Wrapper.m_PlayerA_OpenOrCloseContainer;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/ReplaceProp".
        /// </summary>
        public InputAction @ReplaceProp => m_Wrapper.m_PlayerA_ReplaceProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/UseProp".
        /// </summary>
        public InputAction @UseProp => m_Wrapper.m_PlayerA_UseProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/Attack".
        /// </summary>
        public InputAction @Attack => m_Wrapper.m_PlayerA_Attack;
        /// <summary>
        /// Provides access to the underlying input action "PlayerA/SwitchIndex".
        /// </summary>
        public InputAction @SwitchIndex => m_Wrapper.m_PlayerA_SwitchIndex;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerA; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerAActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerAActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerAActions" />
        public void AddCallbacks(IPlayerAActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerAActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerAActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Evacuate.started += instance.OnEvacuate;
            @Evacuate.performed += instance.OnEvacuate;
            @Evacuate.canceled += instance.OnEvacuate;
            @OpenOrCloseBag.started += instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.performed += instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.canceled += instance.OnOpenOrCloseBag;
            @ChooseProp.started += instance.OnChooseProp;
            @ChooseProp.performed += instance.OnChooseProp;
            @ChooseProp.canceled += instance.OnChooseProp;
            @DiscardProp.started += instance.OnDiscardProp;
            @DiscardProp.performed += instance.OnDiscardProp;
            @DiscardProp.canceled += instance.OnDiscardProp;
            @OpenOrCloseContainer.started += instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.performed += instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.canceled += instance.OnOpenOrCloseContainer;
            @ReplaceProp.started += instance.OnReplaceProp;
            @ReplaceProp.performed += instance.OnReplaceProp;
            @ReplaceProp.canceled += instance.OnReplaceProp;
            @UseProp.started += instance.OnUseProp;
            @UseProp.performed += instance.OnUseProp;
            @UseProp.canceled += instance.OnUseProp;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SwitchIndex.started += instance.OnSwitchIndex;
            @SwitchIndex.performed += instance.OnSwitchIndex;
            @SwitchIndex.canceled += instance.OnSwitchIndex;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerAActions" />
        private void UnregisterCallbacks(IPlayerAActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Evacuate.started -= instance.OnEvacuate;
            @Evacuate.performed -= instance.OnEvacuate;
            @Evacuate.canceled -= instance.OnEvacuate;
            @OpenOrCloseBag.started -= instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.performed -= instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.canceled -= instance.OnOpenOrCloseBag;
            @ChooseProp.started -= instance.OnChooseProp;
            @ChooseProp.performed -= instance.OnChooseProp;
            @ChooseProp.canceled -= instance.OnChooseProp;
            @DiscardProp.started -= instance.OnDiscardProp;
            @DiscardProp.performed -= instance.OnDiscardProp;
            @DiscardProp.canceled -= instance.OnDiscardProp;
            @OpenOrCloseContainer.started -= instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.performed -= instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.canceled -= instance.OnOpenOrCloseContainer;
            @ReplaceProp.started -= instance.OnReplaceProp;
            @ReplaceProp.performed -= instance.OnReplaceProp;
            @ReplaceProp.canceled -= instance.OnReplaceProp;
            @UseProp.started -= instance.OnUseProp;
            @UseProp.performed -= instance.OnUseProp;
            @UseProp.canceled -= instance.OnUseProp;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SwitchIndex.started -= instance.OnSwitchIndex;
            @SwitchIndex.performed -= instance.OnSwitchIndex;
            @SwitchIndex.canceled -= instance.OnSwitchIndex;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerAActions.UnregisterCallbacks(IPlayerAActions)" />.
        /// </summary>
        /// <seealso cref="PlayerAActions.UnregisterCallbacks(IPlayerAActions)" />
        public void RemoveCallbacks(IPlayerAActions instance)
        {
            if (m_Wrapper.m_PlayerAActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerAActions.AddCallbacks(IPlayerAActions)" />
        /// <seealso cref="PlayerAActions.RemoveCallbacks(IPlayerAActions)" />
        /// <seealso cref="PlayerAActions.UnregisterCallbacks(IPlayerAActions)" />
        public void SetCallbacks(IPlayerAActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerAActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerAActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerAActions" /> instance referencing this action map.
    /// </summary>
    public PlayerAActions @PlayerA => new PlayerAActions(this);

    // PlayerB
    private readonly InputActionMap m_PlayerB;
    private List<IPlayerBActions> m_PlayerBActionsCallbackInterfaces = new List<IPlayerBActions>();
    private readonly InputAction m_PlayerB_Move;
    private readonly InputAction m_PlayerB_OpenOrCloseContainer;
    private readonly InputAction m_PlayerB_DiscardProp;
    private readonly InputAction m_PlayerB_ChooseProp;
    private readonly InputAction m_PlayerB_Evacuate;
    private readonly InputAction m_PlayerB_OpenOrCloseBag;
    private readonly InputAction m_PlayerB_ReplaceProp;
    private readonly InputAction m_PlayerB_UseProp;
    private readonly InputAction m_PlayerB_Attack;
    private readonly InputAction m_PlayerB_SwitchIndex;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerB".
    /// </summary>
    public struct PlayerBActions
    {
        private @PlayingInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerBActions(@PlayingInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_PlayerB_Move;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/OpenOrCloseContainer".
        /// </summary>
        public InputAction @OpenOrCloseContainer => m_Wrapper.m_PlayerB_OpenOrCloseContainer;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/DiscardProp".
        /// </summary>
        public InputAction @DiscardProp => m_Wrapper.m_PlayerB_DiscardProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/ChooseProp".
        /// </summary>
        public InputAction @ChooseProp => m_Wrapper.m_PlayerB_ChooseProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/Evacuate".
        /// </summary>
        public InputAction @Evacuate => m_Wrapper.m_PlayerB_Evacuate;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/OpenOrCloseBag".
        /// </summary>
        public InputAction @OpenOrCloseBag => m_Wrapper.m_PlayerB_OpenOrCloseBag;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/ReplaceProp".
        /// </summary>
        public InputAction @ReplaceProp => m_Wrapper.m_PlayerB_ReplaceProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/UseProp".
        /// </summary>
        public InputAction @UseProp => m_Wrapper.m_PlayerB_UseProp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/Attack".
        /// </summary>
        public InputAction @Attack => m_Wrapper.m_PlayerB_Attack;
        /// <summary>
        /// Provides access to the underlying input action "PlayerB/SwitchIndex".
        /// </summary>
        public InputAction @SwitchIndex => m_Wrapper.m_PlayerB_SwitchIndex;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerB; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerBActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerBActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerBActions" />
        public void AddCallbacks(IPlayerBActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerBActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerBActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @OpenOrCloseContainer.started += instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.performed += instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.canceled += instance.OnOpenOrCloseContainer;
            @DiscardProp.started += instance.OnDiscardProp;
            @DiscardProp.performed += instance.OnDiscardProp;
            @DiscardProp.canceled += instance.OnDiscardProp;
            @ChooseProp.started += instance.OnChooseProp;
            @ChooseProp.performed += instance.OnChooseProp;
            @ChooseProp.canceled += instance.OnChooseProp;
            @Evacuate.started += instance.OnEvacuate;
            @Evacuate.performed += instance.OnEvacuate;
            @Evacuate.canceled += instance.OnEvacuate;
            @OpenOrCloseBag.started += instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.performed += instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.canceled += instance.OnOpenOrCloseBag;
            @ReplaceProp.started += instance.OnReplaceProp;
            @ReplaceProp.performed += instance.OnReplaceProp;
            @ReplaceProp.canceled += instance.OnReplaceProp;
            @UseProp.started += instance.OnUseProp;
            @UseProp.performed += instance.OnUseProp;
            @UseProp.canceled += instance.OnUseProp;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @SwitchIndex.started += instance.OnSwitchIndex;
            @SwitchIndex.performed += instance.OnSwitchIndex;
            @SwitchIndex.canceled += instance.OnSwitchIndex;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerBActions" />
        private void UnregisterCallbacks(IPlayerBActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @OpenOrCloseContainer.started -= instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.performed -= instance.OnOpenOrCloseContainer;
            @OpenOrCloseContainer.canceled -= instance.OnOpenOrCloseContainer;
            @DiscardProp.started -= instance.OnDiscardProp;
            @DiscardProp.performed -= instance.OnDiscardProp;
            @DiscardProp.canceled -= instance.OnDiscardProp;
            @ChooseProp.started -= instance.OnChooseProp;
            @ChooseProp.performed -= instance.OnChooseProp;
            @ChooseProp.canceled -= instance.OnChooseProp;
            @Evacuate.started -= instance.OnEvacuate;
            @Evacuate.performed -= instance.OnEvacuate;
            @Evacuate.canceled -= instance.OnEvacuate;
            @OpenOrCloseBag.started -= instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.performed -= instance.OnOpenOrCloseBag;
            @OpenOrCloseBag.canceled -= instance.OnOpenOrCloseBag;
            @ReplaceProp.started -= instance.OnReplaceProp;
            @ReplaceProp.performed -= instance.OnReplaceProp;
            @ReplaceProp.canceled -= instance.OnReplaceProp;
            @UseProp.started -= instance.OnUseProp;
            @UseProp.performed -= instance.OnUseProp;
            @UseProp.canceled -= instance.OnUseProp;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @SwitchIndex.started -= instance.OnSwitchIndex;
            @SwitchIndex.performed -= instance.OnSwitchIndex;
            @SwitchIndex.canceled -= instance.OnSwitchIndex;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerBActions.UnregisterCallbacks(IPlayerBActions)" />.
        /// </summary>
        /// <seealso cref="PlayerBActions.UnregisterCallbacks(IPlayerBActions)" />
        public void RemoveCallbacks(IPlayerBActions instance)
        {
            if (m_Wrapper.m_PlayerBActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerBActions.AddCallbacks(IPlayerBActions)" />
        /// <seealso cref="PlayerBActions.RemoveCallbacks(IPlayerBActions)" />
        /// <seealso cref="PlayerBActions.UnregisterCallbacks(IPlayerBActions)" />
        public void SetCallbacks(IPlayerBActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerBActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerBActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerBActions" /> instance referencing this action map.
    /// </summary>
    public PlayerBActions @PlayerB => new PlayerBActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerA" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerAActions.AddCallbacks(IPlayerAActions)" />
    /// <seealso cref="PlayerAActions.RemoveCallbacks(IPlayerAActions)" />
    public interface IPlayerAActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Evacuate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEvacuate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenOrCloseBag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenOrCloseBag(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DiscardProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDiscardProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenOrCloseContainer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenOrCloseContainer(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReplaceProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReplaceProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Attack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAttack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchIndex" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchIndex(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerB" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerBActions.AddCallbacks(IPlayerBActions)" />
    /// <seealso cref="PlayerBActions.RemoveCallbacks(IPlayerBActions)" />
    public interface IPlayerBActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenOrCloseContainer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenOrCloseContainer(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DiscardProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDiscardProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChooseProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChooseProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Evacuate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEvacuate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenOrCloseBag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenOrCloseBag(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ReplaceProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReplaceProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseProp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseProp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Attack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAttack(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchIndex" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchIndex(InputAction.CallbackContext context);
    }
}
